plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-packaging

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'bin/*'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 8

Metrics/ClassLength:
  Max: 250

Naming/VariableNumber:
  Exclude:
    - 'lib/zai_payment/resources/user.rb'