name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Before submitting, please check if a similar issue already exists.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you're experiencing
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize client with '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What did happen?
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample to reproduce the issue
      placeholder: |
        ```ruby
        # Your code here
        ```
      render: ruby
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste the error message or stack trace
      placeholder: |
        ```
        Paste error output here
        ```
      render: shell
    validations:
      required: false

  - type: input
    id: gem-version
    attributes:
      label: Gem Version
      description: What version of zai_payment are you using?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: ruby-version
    attributes:
      label: Ruby Version
      description: What version of Ruby are you using?
      placeholder: e.g., 3.2.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g., macOS 13.0, Ubuntu 22.04, Windows 11
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other relevant information?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have read the [documentation](https://rubydoc.info/gems/zai_payment)
          required: true
        - label: I have provided all the required information above
          required: true

